apiVersion: v1
kind: Service
metadata:
  name: soc-backend
  namespace: soc-logging
spec:
  selector:
    app: soc-backend
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: soc-frontend
  namespace: soc-logging
spec:
  selector:
    app: soc-frontend
  ports:
    - port: 80
      targetPort: 5173
